#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific TeX Live version
#
# Usage: tlenv shell <version>
#        tlenv shell -
#        tlenv shell --unset
#
# Sets a shell-specific TeX Live version by setting the `TLENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a TeX Live version known to tlenv.
# The special version string `system' will use your default system TeX Live.
# Run `tlenv versions' for a list of available TeX Live versions.
#
# When `-` is passed instead of the version string, the previously set
# version will be restored. With `--unset`, the `TLENV_VERSION`
# environment variable gets unset, restoring the environment to the
# state before the first `tlenv shell` call.

set -e
[ -n "$TLENV_DEBUG" ] && set -x

# Provide tlenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec tlenv-versions --bare
fi

version="$1"
shell="$(basename "${TLENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$TLENV_VERSION" ]; then
    echo "tlenv: no shell-specific version configured" >&2
    exit 1
  else
    echo 'echo "$TLENV_VERSION"'
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo 'set -gu TLENV_VERSION_OLD "$TLENV_VERSION"'
    echo "set -e TLENV_VERSION"
    ;;
  * )
    echo 'TLENV_VERSION_OLD="${TLENV_VERSION-}"'
    echo "unset TLENV_VERSION"
    ;;
  esac
  exit
fi

if [ "$version" = "-" ]; then
  case "$shell" in
  fish )
    cat <<EOS
if set -q TLENV_VERSION_OLD
  if [ -n "\$TLENV_VERSION_OLD" ]
    set TLENV_VERSION_OLD_ "\$TLENV_VERSION"
    set -gx TLENV_VERSION "\$TLENV_VERSION_OLD"
    set -gu TLENV_VERSION_OLD "\$TLENV_VERSION_OLD_"
    set -e TLENV_VERSION_OLD_
  else
    set -gu TLENV_VERSION_OLD "\$TLENV_VERSION"
    set -e TLENV_VERSION
  end
else
  echo "tlenv: TLENV_VERSION_OLD is not set" >&2
  false
end
EOS
    ;;
  * )
    cat <<EOS
if [ -n "\${TLENV_VERSION_OLD+x}" ]; then
  if [ -n "\$TLENV_VERSION_OLD" ]; then
    TLENV_VERSION_OLD_="\$TLENV_VERSION"
    export TLENV_VERSION="\$TLENV_VERSION_OLD"
    TLENV_VERSION_OLD="\$TLENV_VERSION_OLD_"
    unset TLENV_VERSION_OLD_
  else
    TLENV_VERSION_OLD="\$TLENV_VERSION"
    unset TLENV_VERSION
  fi
else
  echo "tlenv: TLENV_VERSION_OLD is not set" >&2
  false
fi
EOS
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if tlenv-prefix "$version" >/dev/null; then
  if [ "$version" != "$TLENV_VERSION" ]; then
    case "$shell" in
    fish )
      echo 'set -gu TLENV_VERSION_OLD "$TLENV_VERSION"'
      echo "set -gx TLENV_VERSION \"$version\""
      ;;
    * )
      echo 'TLENV_VERSION_OLD="${TLENV_VERSION-}"'
      echo "export TLENV_VERSION=\"$version\""
      ;;
    esac
  fi
else
  echo "false"
  exit 1
fi
