#!/usr/bin/env bash
# Usage: tlenv version-file [<dir>]
# Summary: Detect the file that sets the current tlenv version
set -e
[ -n "$TLENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -s "${root}/.texlive-version" ]; then
      echo "${root}/.texlive-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$TLENV_DIR" || {
    [ "$TLENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${TLENV_ROOT}/version"
fi
