#!/usr/bin/env bash
set -e
[ -n "$TLENV_DEBUG" ] && set -x

# Provide tlenv completions
if [ "$1" = "--complete" ]; then
  exec tlenv-rehash --complete
fi

shell="$(basename "${TLENV_SHELL:-$SHELL}")"

# When tlenv shell integration is enabled, delegate to tlenv-rehash,
# then tell the shell to empty its command lookup cache.
tlenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
