#!/usr/bin/env bash
# Usage: tlenv version-file-write <file> <version>

set -e
[ -n "$TLENV_DEBUG" ] && set -x

TLENV_VERSION_FILE="$1"
TLENV_VERSION="$2"

if [ -z "$TLENV_VERSION" ] || [ -z "$TLENV_VERSION_FILE" ]; then
  tlenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
tlenv-prefix "$TLENV_VERSION" >/dev/null

# Write the version out to disk.
echo "$TLENV_VERSION" > "$TLENV_VERSION_FILE"
