#!/usr/bin/env bash
# Summary: Explain how the current TeX Live version is set
set -e
[ -n "$TLENV_DEBUG" ] && set -x

unset TLENV_VERSION_ORIGIN

OLDIFS="$IFS"
IFS=$'\n' scripts=(`tlenv-hooks version-origin`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -n "$TLENV_VERSION_ORIGIN" ]; then
  echo "$TLENV_VERSION_ORIGIN"
elif [ -n "$TLENV_VERSION" ]; then
  echo "TLENV_VERSION environment variable"
else
  tlenv-version-file
fi
