#!/usr/bin/env bash
# Usage: tlenv completions <command> [arg1 arg2...]

set -e
[ -n "$TLENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  tlenv-help --usage completions >&2
  exit 1
fi

# Provide tlenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec tlenv-commands
fi

COMMAND_PATH="$(command -v "tlenv-$COMMAND" || command -v "tlenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide tlenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
