#!/usr/bin/env bash
# Summary: Show the current TeX Live version and its origin
#
# Shows the currently selected TeX Live version and how it was
# selected. To obtain only the version string, use `tlenv
# version-name'.

set -e
[ -n "$TLENV_DEBUG" ] && set -x

version_name="$(tlenv-version-name)"
version_origin="$(tlenv-version-origin)"

if [ "$version_origin" = "${TLENV_ROOT}/version" ] && [ ! -e "$version_origin" ]; then
  echo "$version_name"
else
  echo "$version_name (set by $version_origin)"
fi
