#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export TLENV_DEBUG=1
  shift
fi

if [ -n "$TLENV_DEBUG" ]; then
  # https://wiki-dev.bash-hackers.org/scripting/debuggingtips#making_xtrace_more_useful
  export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "tlenv: $*"
    fi
  } >&2
  exit 1
}

if enable -f "${BASH_SOURCE%/*}"/../libexec/tlenv-realpath.dylib realpath 2>/dev/null; then
  abs_dirname() {
    local path
    path="$(realpath "$1")"
    echo "${path%/*}"
  }
else
  [ -z "$TLENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"

  READLINK=$(type -p greadlink readlink 2>/dev/null | head -n1)
  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

  resolve_link() {
    $READLINK "$1"
  }

  abs_dirname() {
    local cwd="$PWD"
    local path="$1"

    while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
  }
fi

if [ -z "${TLENV_ROOT}" ]; then
  TLENV_ROOT="${HOME}/.tlenv"
else
  TLENV_ROOT="${TLENV_ROOT%/}"
fi
export TLENV_ROOT

if [ -z "${TLENV_DIR}" ]; then
  TLENV_DIR="$PWD"
else
  [[ $TLENV_DIR == /* ]] || TLENV_DIR="$PWD/$TLENV_DIR"
  cd "$TLENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$TLENV_DIR'"
  TLENV_DIR="$PWD"
  cd "$OLDPWD"
fi
export TLENV_DIR

[ -n "$TLENV_ORIG_PATH" ] || export TLENV_ORIG_PATH="$PATH"

shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${TLENV_ROOT}/plugins/"*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
export PATH="${bin_path}:${PATH}"

TLENV_HOOK_PATH="${TLENV_HOOK_PATH}:${TLENV_ROOT}/tlenv.d"
if [ "${bin_path%/*}" != "$TLENV_ROOT" ]; then
  # Add tlenv's own `tlenv.d` unless tlenv was cloned to TLENV_ROOT
  TLENV_HOOK_PATH="${TLENV_HOOK_PATH}:${bin_path%/*}/tlenv.d"
fi
TLENV_HOOK_PATH="${TLENV_HOOK_PATH}:/usr/local/etc/tlenv.d:/etc/tlenv.d:/usr/lib/tlenv/hooks"
for plugin_hook in "${TLENV_ROOT}/plugins/"*/etc/tlenv.d; do
  TLENV_HOOK_PATH="${TLENV_HOOK_PATH}:${plugin_hook}"
done
TLENV_HOOK_PATH="${TLENV_HOOK_PATH#:}"
export TLENV_HOOK_PATH

shopt -u nullglob


command="$1"
case "$command" in
"" )
  { tlenv---version
    tlenv-help
  } | abort
  ;;
-v | --version )
  exec tlenv---version
  ;;
-h | --help )
  exec tlenv-help
  ;;
* )
  command_path="$(command -v "tlenv-$command" || true)"
  if [ -z "$command_path" ]; then
    if [ "$command" == "shell" ]; then
      abort "shell integration not enabled. Run \`tlenv init' for instructions."
    else
      abort "no such command \`$command'"
    fi
  fi

  shift 1
  if [ "$1" = --help ]; then
    if [[ "$command" == "sh-"* ]]; then
      echo "tlenv help \"$command\""
    else
      exec tlenv-help "$command"
    fi
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
